agenda_app/contact/urls.py
from contact import views
from django.urls import path

app_name = 'contact'

urlpatterns = [
    # path('<int:contact_id>/', views.contact, name='contact'),
    path('contact/<int:contact_id>/detail/', views.contact, name='contact'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),  # logged in and owner
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),  # logged in and owner
    path('contact/create/', views.create, name='create'),  # logged in
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
    # contact CRUD
    # path('contact/<int:contact_id>/update/', views.contact, name='contact'),
    # path('contact/<int:contact_id>/delete/', views.contact, name='contact'),
    # user
    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),  # logged in
    path('user/update/', views.user_update, name='user_update'),  # logged in
]

agenda_app/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agenda_app/contact/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# id (primary key - automático)
# first_name (string), last_name (string), phone (string)
# email (email), created_date (date), description (text)
# category (foreign key), show (boolean), picture (imagem)
# owner (foreign key)

# string is limited to 255 - CharField
# text not - TextField


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(
        max_length=50,
        verbose_name='Telefone',
    )
    email = models.EmailField(
        max_length=254,
        blank=True,
        verbose_name='E-MAIL',
    )
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True
    )
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

agenda_app/contact/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from . import models


class ContactForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'class-a class-b', 'placeholder': 'First name.'}
        ),
        label='Your First Name:',
    )
    new_widget = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'class-a class-b',
                'placeholder': 'I didn\'t come from models.',
            }
        ),
        label='I am a new widget:',
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['phone'].widget.attrs.update(
            {  # html
                'class': 'class-a class-b',
                'placeholder': 'Phone. This is from a widget using __init__.',
            }
        )

    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        )
    )

    class Meta:
        model = models.Contact
        fields = (
            'first_name',
            'last_name',
            'phone',
            'email',
            'description',
            'category',
            'picture',
        )

    def clean(self):  # access to the data before saving.
        cleaned_data = self.cleaned_data
        # print(cleaned_data)

        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            self.add_error(
                'last_name',
                ValidationError(
                    'Last name can\'t be equal to first name.', code='invalid'
                ),
            )

        # self.add_error('first_name', ValidationError('Error Message 1', code='invalid'))
        # self.add_error(
        #     None, ValidationError('Error Message: non_field', code='invalid')  # non_field_errors
        # )
        return super().clean()

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')

        if last_name == 'ABC':
            self.add_error(
                'last_name',
                ValidationError('I\'m from add_error! clean_last_name', code='invalid'),
            )

        return last_name


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        min_length=3,
        error_messages={
            'required': 'I change the required message. This is still required.'
        },
    )
    last_name = forms.CharField(
        required=True,
        min_length=3,
    )
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError(
                    'This email is already being used.',
                ),
            )


class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={'min_length': 'Please, add more than 2 letters.'},
    )

    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={'min_length': 'Please, add more than 2 letters.'},
    )

    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label='Password 2',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)

        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2', ValidationError('The passwords are not the same.')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')

        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('This email already exists.', code='invalid'),
                )
        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error('password1', ValidationError(errors))

        return password1

agenda_app/contact/views/contact_forms.py
from contact.forms import ContactForm
from contact.models import Contact
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse


@login_required(login_url='contact:login')
def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():  # without errors
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)  # contact.id
    else:
        context = {
            'form': ContactForm(),  # empty; GET
            'form_action': form_action,
        }

    return render(request, 'contact/create.html', context)


@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True, owner=request.user
    )  # don't forget the pk
    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':
        form = ContactForm(
            request.POST, request.FILES, instance=contact
        )  # instance of contact that exists
        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():  # without errors
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            return redirect('contact:update', contact_id=contact.pk)  # contact.id
    else:
        context = {
            'form': ContactForm(instance=contact),  # empty; GET
            'form_action': form_action,
        }

    return render(request, 'contact/create.html', context)


@login_required(login_url='contact:login')
def delete(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation,
        },
    )

agenda_app/contact/views/contact_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render

from contact.models import Contact


def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')

    # print(contacts.query)

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # context = {'page_obj': page_obj, 'site_title': 'Contatos - '}

    context = {'page_obj': page_obj, 'site_title': 'Contatos - '}

    return render(request, 'contact/index.html', context)


def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = (
        Contact.objects.filter(show=True)
        .filter(
            Q(first_name__icontains=search_value)
            | Q(last_name__icontains=search_value)
            | Q(phone__icontains=search_value)
            | Q(email__icontains=search_value)
        )  # OR
        .order_by('-id')
    )

    # print(contacts.query)

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj, 'site_title': 'Search - '}

    return render(request, 'contact/index.html', context)


def contact(request, contact_id):
    # get - único
    # filter - queryset
    # single_contact = Contact.objects.get(pk=contact_id)
    # single_contact = Contact.objects.filter(pk=contact_id).first()
    # single_contact = get_object_or_404(Contact.objects.filter(pk=contact_id, show=True))  # AND
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)  # AND

    contact_name = f'{single_contact.first_name} {single_contact.last_name} - '
    context = {
        'contact': single_contact,
        'site_title': contact_name,
    }

    return render(request, 'contact/contact.html', context)

agenda_app/contact/views/user_forms.py
from contact.forms import RegisterForm, RegisterUpdateForm
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render


def register(request):
    form = RegisterForm()

    messages.info(request, 'Any text.')

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'User successfully registered.')
            return redirect('contact:index')

    return render(
        request,
        'contact/register.html',
        {
            'form': form,
        },
    )


@login_required(login_url='contact:login')
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form,
            },
        )

    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form,
            },
        )
    form.save()
    return redirect('contact:user_update')


def login_view(request):

    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)  # really login
            messages.success(request, 'You have successfully logged in.')
            return redirect('contact:index')
        messages.error(request, 'Invalid login!')

    return render(
        request,
        'contact/login.html',
        {
            'form': form,
        },
    )

@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contact:login')

agenda_app/contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
  <div class="single-contact">
    <h1 class="single-contact-name">
      {{ contact.first_name }} {{ contact.last_name }}
    </h1>

    <p><b>ID:</b> {{ contact.id }}</p>
    <p><b>Email:</b> {{ contact.email }}</p>
    <p><b>Phone:</b> {{ contact.phone }}</p>
    <p><b>Created Date:</b> {{ contact.created_date }}</p>
    <p><b>Description:</b> {{ contact.description }}</p>
    <p><b>Category:</b> {{ contact.category }}</p>

    {% if contact.picture %}
    <p>
        <img src="{{ contact.picture.url }}" alt="{{  contact.first_name }} {{ contact.last_name }}">
    </p>
    {% endif %}

    {% if contact.owner %}
    <p>
        <b>Owner: </b>{{ contact.owner }}
    </p>
    {% endif %}
    
    {% if user == contact.owner %}  {# user or request.user #}
    <div class="contact-links">
        <a class="btn btn-link" href="{% url "contact:update" contact.id %}">Update</a>

        <form action="{% url "contact:delete" contact.id %}" method="post">
            {% csrf_token %}

            {% if confirmation == 'no' %}
            <input type="hidden" name="confirmation" value="yes">
            <button class="btn btn-link btn-delete" type="submit">Confirm?</button>
            {% else %}
            <button class="btn btn-link btn-delete" type="submit">Delete</button>
            {% endif %}
        </form>
    </div>
    {% endif %}
  </div>
{% endblock content %}

agenda_app/contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Contact</h2>

    {# form_action for use reverse in the views #}
    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>
          {% if field.name == 'picture' and field.value.url %}
                <div class="form-group">
                    <img src="{{ field.value.url }}" alt="">
                </div>
            {% endif %}
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

agenda_app/contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Contacts
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Full name</th>
                    {% comment %} <th class="table-header">First name</th>
                    <th class="table-header">Last name</th> {% endcomment %}
                    <th class="table-header">phone</th>
                    <th class="table-header">Email</th>
                </tr>
            </thead>
            <tbody>
                {% for contact in page_obj %}
                {% if contact.owner == user %}
                    <tr class="table-row">
                        <td class="table-cel">
                            {{  contact.id  }}
                        </td>
                        <td class="table-cel">
                            <a href="{% url "contact:contact" contact.id %}" class="table-link">
                                {% comment %} {{  contact.first_name  }} {{  contact.last_name  }} {% endcomment %}
                                {{ contact }} {# __str__ #}
                            </a>
                        </td>
                        {% comment %} <td class="table-cel">
                            <a href="#" class="table-link">
                                {{  contact.first_name }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a href="#" class="table-link">
                                {{  contact.last_name  }}
                            </a>
                        </td> {% endcomment %}
                        <td class="table-cel">
                                {{  contact.phone  }}
                        </td>
                        <td class="table-cel">
                                {{  contact.email  }}
                        </td>
                    </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            No contacts found.
        </h1>
    </div>
{% endif %}
{% endblock content %}

agenda_app/contact/templates/contact/login.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Login</h2>

    {% if user.is_authenticated %}
        <p>You have logged in: <strong>{{ user }}</strong></p>
        <p><a href="{% url "contact:logout" %}">Logout here</a></p>
    {% else %}
        {% include "contact/partials/_user-form.html" %}
    {% endif %}
    
  </div>
{% endblock content %}

agenda_app/contact/templates/contact/register.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Register</h2>

    {# form_action for use reverse in the views #}
    <form 
      action="{{ form_action }}"
      method="POST"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>
          
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

agenda_app/contact/templates/contact/user_update.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">
        <h2>Update User</h2>

        {% include "contact/partials/_user-form.html" %}
    </div>
{% endblock content %}